spring:
    profiles:

    datasource:
        url: jdbc:mysql://localhost:3306/prototype?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: password
        hikari:
            initialization-fail-timeout: 60000

    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
    error:
        include-stacktrace: never
        include-exception: false
        whitelabel.enabled: false

api:
    admin:
        email: admin@email.com
        password: admin-password

    jwt:
        secret: n2r5u8x/A%D*G-KaPdSgVkYp3s6v9y$B&E(H+MbQeThWmZq4t7w!z%C*F-J@NcRf

    swagger-ui:
        enabled: true
